name: Docker Image CI

on:
  push:
    branches:
    - develop

jobs:

  build_test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: Build the test image and run it
      run: docker build . --file test.Dockerfile --tag ${{ secrets.acr_registry }}$GITHUB_REPOSITORY:test


# yontan need to add a config file with secrets 
    - name: Run test
      run: docker run --env-file $env_file ${{ secrets.acr_registry }}$GITHUB_REPOSITORY:test 
      id: test
    
    
    - name: Build the develop branch
      run: docker build . --file test.Dockerfile --tag ${{ secrets.acr_registry }}$GITHUB_REPOSITORY:develop
    



    - name: Docker Login 
    - uses: azure/docker-login@v1
      with:
       login-server: ${{ secrets.acr_registry }}
       username: ${{ secrets.acr_username }}
       password: ${{ secrets.acr_password }}
       
    - name: Push container
      run: docker push ${{ secrets.acr_registry }}$GITHUB_REPOSITORY:develop
      if: steps.test.status == success()








